---
title: "Molecular Dynamics"
author: "Fadjar Fathurrahman"
format:
  revealjs:
    smaller: true
    scrollable: true
---

## Energi potensial

Energi interaksi (potensial) $u(r_{ij})$, antara dua partikel yang terletak pada $\mathbf{r}_{i}$
dan $\mathbf{r}_{j}$ dapat dituliskan sebagai berikut.
$$
u(r_{ij}) = \begin{cases}
4 \epsilon \left[\left(
    \dfrac{\sigma}{r_{ij}}\right)^{12} -
    \left(\dfrac{\sigma}{r_{ij}}\right)^{6}\right] & r_{ij} < r_{c} \\
0 & r_{ij}>r_{c}
\end{cases}
$$
dengan
$\mathbf{r}_{ij} = \mathbf{r}_{i} - \mathbf{r_{j}}$ dan
$r_{ij}=\left|\mathbf{r}_{ij}\right|$.

Potensial bola lunak:
$$
u(r_{ij}) = \begin{cases}
4\epsilon\left[\left(\dfrac{\sigma}{r_{ij}}\right)^{12} - \left(\dfrac{\sigma}{r_{ij}}\right)^{6}\right]+\epsilon & r_{ij}<r_{c}=2^{1/6}\sigma\\
0 & r_{ij}>r_{c}
\end{cases}
$$

Gaya yang diakibatkan oleh medan potensial (konservatif) $u(r)$ adalah
$$
\mathbf{f} = -\nabla u(r)
$$

Gaya yang dikerjakan oleh atom ke-$j$ terhadap atom ke-$i$ dapat dituliskan
sebagai
$$
\mathbf{f}_{ij} = \left(\dfrac{48\epsilon}{\sigma^{2}}\right)
\left[\left(\dfrac{\sigma}{r_{ij}}\right)^{14} -
\dfrac{1}{2}\left(\dfrac{\sigma}{r_{ij}}\right)^{8}
\right]\mathbf{r}_{ij}
$$

Persamaan gerak:
$$
m \ddot{\mathbf{r}_{i}} = \mathbf{f}_{i} = \sum_{j\neq i}^{N_{m}} \mathbf{f}_{ij}
$$

Hukum ketiga Newton (aksi-reaksi):
$$
\mathbf{f}_{ij} = -\mathbf{f}_{ji}
$$

## Satuan (argon cair (liquid argon))

- Lengths are expressed in $\sigma$ which is equal to 3.4 armstrong

- Energies are expressed in $\epsilon/k_B = 120 K$, or
  $\epsilon = 120 \times 1.3806 \times 10^{-16}$ erg/atom

- mass of an argon atom: $m = 39.95 \times 1.6746 \times 10^{-24}$ g

- time unit in $2.161 \times 10^{-12}$ s



## Persamaan pada satuan MD (argon cair)

Untuk dimensi panjang: $r \rightarrow r\sigma$

Untuk energi: $e \rightarrow e\epsilon$

Untuk waktu: $t \rightarrow t\sqrt{m\sigma^2/\epsilon}$


Persamaan gerak:
$$
\ddot{\mathbf{r}}_{i} = 48 \sum_{j\neq i}
\left( r_{ij}^{-14} - \frac{1}{2}r_{ij}^{-8} \right)
\mathbf{r}_{ij}
$$

Energi kinetik:
$$
E_{K} = \frac{1}{2N_m} \sum_{i=1}^{N_m} \mathbf{v}_{i}^{2}
$$

Energi potensial:
$$
E_{U} = \frac{4}{N_m} \sum_{1\leq i \le j \leq N_m}
\left( r_{ij}^{-12} - r_{ij}^{-6} \right)
$$


Satuan dari temperatur adalah $\epsilon/k_B$ dan karena setiap derajat kebebasan translasi
memberikan kontribusi sebesar $k_B T/2$ pada energi kinetik, temperatur dari $d$-dimensional
($d$ adalah 2 atau 3) adalah
$$
T = \frac{1}{dN_m} \sum_{i} \mathbf{v}_{i}^{2}
$$

Pada persamaan di atas telah digunakan 
$k_B = 1$ sehingga satuan temperatur  dari MD juga telah terdefinisikan. 


## Integrasi persamaan gerak

Jika $\Delta t$ melambangkan ukuran langkah waktu yang digunakan pada integrasi
numerik, maka formula integrasi diaplikasikan untuk setiap komponen dari koordinat
atom dan kecepatan.
Untuk kecepatan digunakan:
$$
\mathbf{v}_{i}\left(t + \frac{h}{2}\right) =
\mathbf{v}_{i}\left(t - \frac{h}{2}\right) + \Delta t \mathbf{a}_{i}(t)
$$
dan untuk posisi digunakan
$$
\mathbf{r}_{i}\left(t + h\right) =
\mathbf{r}_{i}\left(t\right) + \Delta t \mathbf{v}_{i}\left(t + \frac{h}{2}\right)
$$

Metode ini dinamakan "leapfrog"
karena posisi dan kecepatan dievaluasi pada waktu yang berbeda. Jika
estimasi nilai untuk kecepatan diperlukan pada waktu ketika posisi baru dihitung
maka kita dapat menggunakan:
$$
\mathbf{v}_{i}(t) = \mathbf{v}_{i}(t - h/2) +
\frac{h}{2}\mathbf{a}_{i}(t)
$$


Formulasi alternatif
$$
\begin{align}
\mathbf{v}(t + \Delta t/2) & = \mathbf{v}_{i}(t) + \frac{\Delta t}{2}\ \mathbf{a}_{i}(t) \\
\mathbf{r}_{i}(t + \Delta t) & = \mathbf{r}_{i}(t) + \Delta t \ \mathbf{v}_{i}(t + \Delta t/2)
\end{align}
$$
Gunakan posisi baru untuk menghitung nilai percepatan yang baru dan perbarui nilai
kecepatan:
$$
\mathbf{v}_{i}(t + \Delta t) = \mathbf{v}_{i}(t + \Delta t/2) +
\frac{\Delta t}{2}\ \mathrm{a}_{i}(t + \Delta t)
$$


## Pengukuran

Tekanan (dengan $k_B = 1$):
$$
PV = N_{m} T + \frac{1}{d}\left\langle \sum_{i}^{N_m} \mathbf{r} \cdot \mathbf{f}_{i} \right\rangle
$$
Untuk kasus dua dimensi, volume diganti dengan luas.

Untuk potensial pasangan, misalnya potensial Lennard-Jones, persamaan
ini dapat ditulis sebagai penjumlahan untuk pasangan atom:
$$
PV = N_{m} T + \frac{1}{d} \left\langle \sum_{i < j} \mathbf{r}_{ij} \cdot
\mathbf{f}_{ij} \right\rangle
$$
atau untuk medan gaya Lennard-Jones:
$$
PV = \frac{1}{2} \left\langle
\sum_{i} \mathbf{v}_{i}^{2} +
48 \sum_{i < j} \mathbf{r}_{ij}^{-12} - \frac{1}{2} r_{ij}^{-6}
\right\rangle
$$

## Equilibrasi

Karakterisasi ekuilibrium pada dasarnya adalah tugas yang sulit, terutama
untuk sistem kecil yang sifatnya sangat berfluktuasi.

Salah satu ukuran dari ekuilibrasi adalah laju di mana
distribusi kecepatan konvergen ke bentuk finalnya. Menurut teori,
distribusi dari kecepatan ini adalah distribusi Maxwell:
$$
f(\mathbf{v}) = \frac{\rho}{(2\pi T)^{d/2}} e^{-v^2/2T}
$$
Setelah integrasi variabel sudut diperoleh:
$$
f(\mathbf{v}) \propto v^{d-1} e^{-v^2/2T}
$$



Fungsi-H Boltzmann memiliki posisi yang penting dalam mekanika statistik.
Fungsi ini didefinisikan sebagai:
$$
H(t) = \int f(\mathbf{v},t) \log f(\mathbf{v},t) \, \mathrm{d}\mathbf{v}
$$
dan dapat dibuktikan bahwa:
$$
\left\langle \frac{\mathrm{d}H}{\mathrm{d}t} \right\rangle \leq 0
$$
Untuk menghitung $H(t)$ kita
dapat menggunakan histogram kecepatan.
Jika faktor konstan diabaikan, maka $H(t)$ dapat diaproksimasi dengan
$$
h(t) = \sum_{n} h_{n} \log \left( \frac{h_n}{v_{n}^{d-1}} \right)
$$




